site_name: ZR Daily Report
site_description: 一个用于生成切削液设备日常库存报告的Python应用程序
site_author: ZR Team

theme:
  name: material
  language: zh
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - 首页: index.md
  - 安装与配置: ../README.md#安装步骤
  - 使用说明: ../README.md#运行程序
  - 技术文档: technical_documentation.md
  - 测试指南: ../tests/TESTING.md
  - 缺陷修复: defect_fixes/defect_fixes_index.md
  - 开发指南: code-quality.md